### PR TITLE
Run yarn run lint.

### PR DESCRIPTION
**Pull request by akurtakov**
Changes done by lint.

Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

### CODE REVIEW

**Comment by skovhus** [comment]
Linting is ensured by CI for all commits. This PR actually failed because the changes made doesn’t not lint correctly. 

It seems you might be using a different tslint or prettier version. Can you remove nose_modules and see if that solves the issue?

**Comment by akurtakov** [comment]
I removed node_modules and got the same results. Anything else you want me to try ?

**Comment by akurtakov** [comment]
Never mind. I haven't reverted last commit and yarn run lint actually bringed it to the master version. Sorry for the noise.

**Comment by skovhus** [comment]
No problem

**Pull request closed without merging**
