### PR TITLE
WIP: A bit of refactoring

### PR DESCRIPTION
**Pull request by skovhus**
WIP: Depends on https://github.com/mads-hartmann/bash-language-server/pull/15

To get into the codebase, I did a few refactorings and documentation fixes for the server and client. 

@mads-hartmann Let me know if you think the flatten functions makes sense to you.

### CODE REVIEW

**Comment by mads-hartmann** [comment]
This is great :) Before refactoring too much more please have a look at my branch `completions-based-on-your-PATH` where I also did some refactoring while trying to add more completions :) I'm happy to merge your two PRs tonight and then try to get my PR in a state where you can review it if you're up for that :)

**Comment by skovhus** [comment]
> Before refactoring too much more please have a look at my branch

Ah, see you did some more since last time I looked. 👍👍 I hope the new tests will help you with the refactoring you are doing...

> can review it if you're up for that

I'm up for that. : )

**Comment by skovhus** [comment]
Feel free to ignore this PR if there are too many conflicts merging this. : )

**Comment by mads-hartmann** [comment]
@skovhus I think it might be easier to merge #17 first and then rebase this one on master :)

**Pull request closed without merging**
