### PR TITLE
Shebang handling

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by przepompownia** [comment]
At the moment this PR merges only the current master into `shebang-handling`. 
See #47

**Comment by skovhus** [comment]
A bit hard to read this PR. Could we rebase the changes on top of master instead of merging?

**Comment by przepompownia** [comment]
TODO
- [ ] review (I am beginner with TS-specific things) 
- [ ] allow to pass glob pattern in another way than using an environment variable
- [ ] more tests
- [ ] allow the user to disable scanning working dir against bash/sh shebang
- [ ] give `hasBashShebang` only the first line of the file (do not match the entire content)

**Comment by skovhus** [comment]
Sorry for stalling here. I've investigated the issue, and it turns out that all bash files (that VS Code can detect) are handled just fine. We don't need to read all the files in a project–unless we want to do just to definition across files (required more work).

Screenshot 2020-02-27 10 41 54
Screenshot 2020-02-27 10 42 01

**Comment by przepompownia** [comment]
It seemed to be natural that the results of `analyze`ing the rest of scripts are accessible for completion and jumping. Indeed: at the moment there is no need to make (almost?) unusable index.

**Comment by skovhus** [comment]
> It seemed to be natural that the results of analyzeing the rest of scripts are accessible for completion and jumping. Indeed: at the moment there is no need to make (almost?) unusable index.

My mistake. It is indeed used for indexing. https://github.com/mads-hartmann/bash-language-server/issues/47#issuecomment-593313329 👍

**Comment by skovhus** [comment]
@przepompownia thanks for your work here. We now handle most of the cases here – except for reading all files. 

I'm reluctant to implement parsing all the files in a project, that shouldn't be necessary. We might consider adding parsing all files without extensions though. :)

**Pull request closed without merging**
