### PR TITLE
Add Jest integration tests

### PR DESCRIPTION
**Pull request by skovhus**
To reduce the feedback loop of improving the language server and make contributions easier, I suggest that we add some Jest integration tests here.

It might have found an issue with the `wordAtPoint` function (see the FIXME).

If we like this, I think next step would be to set up CI. I can look into that if you want. : )

### CODE REVIEW

**Comment by mads-hartmann** [comment]
This is awesome @skovhus. I'm all for adding this to the CI as well. I know it might be a no-brainer but could I get you to write a tiny section in the README about how to run the tests?

**Comment by skovhus** [comment]
I will. : )

**Comment by skovhus** [comment]
@mads-hartmann let me know if the documentation looks good to you.

I also added a travis configuration here.

**Comment by mads-hartmann** [comment]
@skovhus Thanks!

**Pull request merged**
