### PR TITLE
Remove npm install step from VS Code extension

### PR DESCRIPTION
**Pull request by skovhus**
Here we are removing the npm install step by including the new wasm version of the LSP server into the VS Code extension.

I combined some work I did back in June (https://github.com/mads-hartmann/bash-language-server/pull/134/commits) and work done a year ago (https://github.com/mads-hartmann/bash-language-server/pull/72).

Related to https://github.com/mads-hartmann/bash-language-server/issues/131 

### TODO
- [x] combine server with vscode client
- [x] test on OS X
- [x] test on Windows
- [x] documentation

Note on how to test:
```sh
cd vscode-client && vsce package --yarn
code --install-extension <path to package.vix>
```

### CODE REVIEW

**Comment by skovhus** [comment]
@mads-hartmann can you try it out by uninstalling `bash-language-server` (`npm -g uninstall bash-language-server`) and run:

```
cd vscode-client && vsce package --yarn
code --install-extension <path to package.vix>
```

**Comment by mads-hartmann** [comment]
@skovhus Just gave it a go. It works 🎉

**Comment by skovhus** [comment]
@mads-hartmann we should release this :) 

The version number is bumped, so we just need to run the release step. Can you do that?

**Comment by mads-hartmann** [comment]
@skovhus Done, works like a charm 🎉

**Comment by skovhus** [comment]
NICE! <3

**Pull request merged**
